### ISSUE TITLE
Exporting named sub-schemas, not just paths?

### ISSUE THREAD

**Issue by lewisl9029** [geut/openapi-box#1]
Hi there! I gave this library a try on one of our schemas and it seems to be working as described. :)

But in order to replace our current manually written validators we'd also need individual schemas defined in `components.schemas` for typing implementation details, not just the api endpoints defined in paths. Example of what this part of our spec looks like:

```yaml
components:
  schemas:
    Cat: 
      properties:
        name:
          type: string
    Dog: 
      properties:
        name:
          type: string
```

Looks like currently all the types for these schemas are being generated, but hidden inside an internal cache, and identified using hashes instead of names. Curious if you think it'd be straightforward to turn those into an exported object with their actual names as keys instead? E.g. for the above ideally it'd look something like this:

```js
export const components = {
  schemas: {
    Cat: T.Object({
      name: T.String()
    }),
    Dog: T.Object({
      name: T.String()
    })
  },
}
```
